# Generated by Django 3.1.7 on 2025-01-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
