# Generated by Django 5.1.6 on 2025-02-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_extendeduserprofile_apppermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduserprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='extendeduserprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AppPermission',
        ),
        migrations.DeleteModel(
            name='ExtendedUserProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
