# Generated by Django 3.1.7 on 2025-01-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
