# Generated by Django 3.1.7 on 2025-01-31 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='basic_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rate_card',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='time_out',
        ),
    ]
